### ISSUE TITLE
preserve IP address relationships when mapping

### ISSUE THREAD

**Issue by bmr-cymru** [RedHatGov/soscleaner#13]
To increase the diagnostic value of the obfuscated data soscleaner should preserve IP address relationships (i.e. netmask and network vs. host portions).

I'm not 100% sure what such a mapping scheme needs to look like for the general case - it's probably worth running this past some networking folks to get their input.

**Comment by jduncan-rva** [comment]
this is fixed with 358281898b71da0ce32dd8e200f8330e236dc386

**Comment by bmr-cymru** [comment]
Cool! :+1:
