### ISSUE TITLE
Tracebacks encountered when running soscleaner against an unpacked sosreport

### ISSUE THREAD

**Issue by burntasphalt** [RedHatGov/soscleaner#48]
Is this user-error or a bug?  :-)  I encountered the following when running soscleaner against the directory 'sosreport' which contained an expanded sosreport:

[root@laptop 01308802]# soscleaner sosreport
12-10 10:51:43 soscleaner CONSOLE: Log File Created at /tmp/soscleaner-7990507535172329.log
12-10 10:51:43 soscleaner CONSOLE: soscleaner version 0.2.2
12-10 10:51:43 soscleaner WARNING: soscleaner is a tool to help obfuscate sensitive information from an existing sosreport.
12-10 10:51:43 soscleaner WARNING: Please review the content before passing it along to any third party.
12-10 10:51:43 soscleaner CONSOLE: Beginning SOSReport Extraction
12-10 10:51:47 soscleaner CONSOLE: Processing hosts file for better obfuscation coverage
12-10 10:51:47 soscleaner CONSOLE: IP Obfuscation Start Address - 10.230.230.1
12-10 10:51:47 soscleaner CONSOLE: *** SOSCleaner Processing ***
12-10 10:52:03 soscleaner CONSOLE: *** SOSCleaner Statistics ***
12-10 10:52:03 soscleaner CONSOLE: IP Addresses Obfuscated - 81
12-10 10:52:03 soscleaner CONSOLE: Hostnames Obfuscated - 18
12-10 10:52:03 soscleaner CONSOLE: Domains Obfuscated - 0
12-10 10:52:03 soscleaner CONSOLE: Total Files Analyzed - 2318
12-10 10:52:03 soscleaner CONSOLE: *** SOSCleaner Artifacts ***
12-10 10:52:03 soscleaner CONSOLE: Creating IP Report - /tmp/soscleaner-7990507535172329-ip.csv
12-10 10:52:03 soscleaner CONSOLE: Creating Hostname Report - /tmp/soscleaner-7990507535172329-hostname.csv
12-10 10:52:03 soscleaner CONSOLE: Creating Domainname Report - /tmp/soscleaner-7990507535172329-dn.csv
12-10 10:52:03 soscleaner CONSOLE: Creating SOSCleaner Archive - /tmp/soscleaner-7990507535172329.tar.gz
12-10 10:52:09 soscleaner ERROR: [Errno 2] No such file or directory: '/tmp/soscleaner-origin-7990507535172329'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/soscleaner.py", line 350, in _clean_up
    shutil.rmtree(self.origin_path)
  File "/usr/lib64/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/soscleaner-origin-7990507535172329'
12-10 10:52:09 soscleaner CONSOLE: SOSCleaner Complete
[root@laptop 01308802]#

**Comment by jduncan-rva** [comment]
This looks to be remedied by 6eab146
