### ISSUE TITLE
domain name not removed in some files

### ISSUE THREAD

**Issue by abeeson100** [RedHatGov/soscleaner#50]
soscleaner-0.2.2-7

When run against an SOS report generated on a system on a domain of "sandbox.local" the following files still retained the domain "sandbox.local" in their contents:

./sos_commands/postfix/postconf:  mydomain = sandbox.local
./etc/sysconfig/network-scripts/ifcfg-eth0:  DOMAIN="sandbox.local"
./etc/resolv.conf:   search sandbox.local

**Comment by jduncan-rva** [comment]
can you paste in the snippets from your logs, so I can see what was detected to be obfuscated vs. what was missed?

**Comment by abeeson100** [comment]
Hi
I have done a run on an unclass system so I can send you the actual sosreport tar, the soscleaner tar and the logs files...It's 7MB in total but I can't see an obvious way to attach to this issue. Is there another way I can get them to you?

**Comment by abeeson100** [comment]
It appears that the domain is not removed if it is not preceded by a "." - for example "myhost.mydomain.com" will be censored but "mydomain.com" won't be.

**Comment by jduncan-rva** [comment]
Interesting. I'll dig into this in hte next day or so.

**Comment by abeeson100** [comment]
Any luck in chasing this issue down? Would be interested in getting an update with bug fix as we're having to manually work-around at the moment...
